AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "spec/dummy/**/*"
    - "vendor/**/*"

LineLength:
  Max: 80

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: leading

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
