AllCops:
  Exclude:
    - "spec/dummy/**/*"

Layout/DotPosition:
  EnforcedStyle: leading

Metrics/LineLength:
  Max: 80

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
